WORLD_WIDTH = 20
WORLD_HEIGHT = 20

PET_VIEW_RADIUS = 5
PET_VIEW_DIAMETER = 2 * PET_VIEW_RADIUS + 1
PET_FOOD_RESERVE = 10
PETS_INITIONAL_NUMBER = 20

SQUARE_TYPE_EMPTY = 100
SQUARE_TYPE_PET = 101

FOOD_INITIONAL_SQUARES_NUMBER = 100
FOOD_GROW_SPEED = 3
FOOD_CONSUMPTION = 1
FOOD_SQUARE_PORTION = 6
